"""add_patient_info_symptom_duration_to_cases

Revision ID: 461e0b08175e
Revises: 
Create Date: 2026-03-11 10:42:11.087195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461e0b08175e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('patient_info', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('symptom_duration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'symptom_duration')
    op.drop_column('cases', 'patient_info')
    # ### end Alembic commands ###
